name: 💥 httpx - HTTP Web Server probing

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
  httpx-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: 💥 httpx - HTTP Web Server probing
        uses: projectdiscovery/httpx-action@main
        with:
          list: hosts.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: httpx.log
          path: httpx.log
